defaults: &defaults
  site_url: focal.yourdomain.com

development:
  <<: *defaults
  site_url: focal.dev

test:
  <<: *defaults
  site_url: focal.test

production:
  <<: *defaults
  site_url: <%= ENV['FOCAL_SITE_URL'] %>